# Generated by Django 4.0.2 on 2022-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0003_alter_writeus_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=300, verbose_name=' İnfonu Giriniz:')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image5', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='writeus',
            name='author',
            field=models.CharField(default=21, max_length=25, verbose_name='İsim Giriniz'),
            preserve_default=False,
        ),
    ]
