# Generated by Django 4.0.2 on 2022-04-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0005_specialarea_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialarea',
            name='image_info',
            field=models.CharField(default=21, max_length=25, verbose_name='İsim Giriniz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialarea',
            name='image_info2',
            field=models.CharField(default=21, max_length=25, verbose_name='İsim Giriniz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialarea',
            name='image_info3',
            field=models.CharField(default=21, max_length=25, verbose_name='İsim Giriniz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialarea',
            name='image_info4',
            field=models.CharField(default=21, max_length=25, verbose_name='İsim Giriniz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialarea',
            name='image_info5',
            field=models.CharField(default=21, max_length=25, verbose_name='İsim Giriniz'),
            preserve_default=False,
        ),
    ]
