# Generated by Django 4.0.2 on 2022-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0006_specialarea_image_info_specialarea_image_info2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialarea',
            name='image_info',
            field=models.CharField(max_length=15, verbose_name='Mini Resim İnfosu 15 Karakterlik'),
        ),
        migrations.AlterField(
            model_name='specialarea',
            name='image_info2',
            field=models.CharField(max_length=15, verbose_name='Mini Resim İnfosu 15 Karakterlik'),
        ),
        migrations.AlterField(
            model_name='specialarea',
            name='image_info3',
            field=models.CharField(max_length=15, verbose_name='Mini Resim İnfosu 15 Karakterlik'),
        ),
        migrations.AlterField(
            model_name='specialarea',
            name='image_info4',
            field=models.CharField(max_length=15, verbose_name='Mini Resim İnfosu 15 Karakterlik'),
        ),
        migrations.AlterField(
            model_name='specialarea',
            name='image_info5',
            field=models.CharField(max_length=15, verbose_name='Mini Resim İnfosu 15 Karakterlik'),
        ),
    ]
