# Generated by Django 4.0.2 on 2022-04-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0007_alter_specialarea_image_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='İsim Giriniz')),
                ('info', models.CharField(max_length=300, verbose_name='Yorum')),
                ('position', models.CharField(max_length=15, verbose_name='Pozizyon')),
            ],
        ),
    ]
