# Generated by Django 4.0.2 on 2022-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='info',
            field=models.TextField(max_length=300, verbose_name='Yorum'),
        ),
    ]
