# Generated by Django 4.0.2 on 2022-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0010_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parthners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Firma İsmi giriniz')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
    ]
