# Generated by Django 4.0.2 on 2022-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0011_parthners'),
    ]

    operations = [
        migrations.AddField(
            model_name='parthners',
            name='kvvk',
            field=models.FileField(default=21, upload_to='products/katalog/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
