# Generated by Django 4.0.2 on 2022-04-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0012_parthners_kvvk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parthners',
            old_name='kvvk',
            new_name='katalog',
        ),
    ]
