# Generated by Django 4.0.2 on 2022-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0013_rename_kvvk_parthners_katalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parthners',
            name='katalog',
            field=models.FileField(blank=True, null=True, upload_to='products/katalog/%y/%m/%d'),
        ),
    ]
