# Generated by Django 4.0.2 on 2022-04-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0014_alter_parthners_katalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parthners',
            name='katalog',
            field=models.FileField(default=21, upload_to='products/katalog/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
