# Generated by Django 4.0.2 on 2022-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0016_galeri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='info',
            field=models.CharField(default='Ürün Açıklama', max_length=250),
        ),
    ]
