# Generated by Django 4.0.2 on 2022-04-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0017_alter_galeri_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialArea',
        ),
        migrations.DeleteModel(
            name='WriteUS',
        ),
    ]
