# Generated by Django 4.0.2 on 2022-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0018_delete_specialarea_delete_writeus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Slider Author')),
                ('title', models.TextField(max_length=300, verbose_name='Yorum')),
                ('small', models.TextField(max_length=300, verbose_name='Küçük Yazı')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
    ]
