# Generated by Django 4.0.2 on 2022-04-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0019_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='small',
            field=models.CharField(max_length=300, verbose_name='Küçük Yazı'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Yorum'),
        ),
    ]
