# Generated by Django 4.0.2 on 2022-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0021_slider_image2_slider_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='small2',
            field=models.CharField(default=21, max_length=300, verbose_name='Küçük Yazı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='small3',
            field=models.CharField(default=21, max_length=300, verbose_name='Küçük Yazı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title2',
            field=models.CharField(default=21, max_length=300, verbose_name='Yorum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title3',
            field=models.CharField(default=21, max_length=300, verbose_name='Yorum'),
            preserve_default=False,
        ),
    ]
