# Generated by Django 4.0.2 on 2022-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0022_slider_small2_slider_small3_slider_title2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=15, verbose_name='Firma İsmi giriniz')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
            ],
        ),
    ]
