# Generated by Django 4.0.2 on 2022-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0024_alter_about_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=1000, verbose_name='Hakkımızda'),
        ),
    ]
