# Generated by Django 4.0.2 on 2022-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0025_alter_about_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('name', models.CharField(max_length=15, verbose_name='İsim Giriniz')),
                ('restaurant', models.CharField(max_length=15, verbose_name='Restanurant giriniz')),
            ],
        ),
    ]
