# Generated by Django 4.0.2 on 2022-05-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0030_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='bodrum.subcategory'),
            preserve_default=False,
        ),
    ]
