# Generated by Django 4.0.2 on 2022-05-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodrum', '0033_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodrum.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodrum.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='AltCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodrum.category'),
        ),
    ]
